const express = require('express')
const app = express()
app.set('view engine','ejs')
var bodyParser = require('body-parser')
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
const index = require('./routes/index')
const routerTeachers = require('./routes/teachers')
const routerSubjects = require('./routes/subjects')
app.use('/',index)
app.use('/teachers',routerTeachers)
app.use('/subjects',routerSubjects)
app.listen(3000, function(req,res){
  console.log('Listen 3000 success !');
})
